### ISSUE TITLE
ㄴ

### ISSUE THREAD

**Issue by sweaterr** [luckyhj777/MachineLearning#1]
![image](https://cloud.githubusercontent.com/assets/1518919/21962776/5f4e852e-db71-11e6-9bb0-c2112a8bf0bb.png)
![image](https://cloud.githubusercontent.com/assets/1518919/21962778/63756aa0-db71-11e6-824d-28a6e5770c6e.png)

**Comment by luckyhj777** [comment]
@sweaterr Thanks!
